"""Initial schema

Revision ID: 06f1ef6a9dd1
Revises: 
Create Date: 2026-05-05 11:54:39.247727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06f1ef6a9dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs_2025_01')
    op.drop_table('user_permission_overrides')
    op.drop_table('audit_logs_2024_01')
    op.drop_table('tax_declarations')
    op.alter_column('approvals', 'entity_type',
               existing_type=postgresql.ENUM('leave', 'asset_request', 'reimbursement', 'it_action', name='approval_entity'),
               type_=sa.Enum('leave', 'asset_request', 'reimbursement', 'it_action', name='approvalentity'),
               existing_nullable=False)
    op.alter_column('approvals', 'decision',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'escalated', name='approval_decision'),
               type_=sa.Enum('pending', 'approved', 'rejected', 'escalated', name='approvaldecision'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::approval_decision"))
    op.drop_index(op.f('idx_approvals_approver'), table_name='approvals')
    op.drop_index(op.f('idx_approvals_entity'), table_name='approvals')
    op.alter_column('asset_requests', 'asset_type',
               existing_type=postgresql.ENUM('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='asset_type'),
               type_=sa.Enum('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='assettype'),
               existing_nullable=False)
    op.alter_column('asset_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'manager_approved', 'it_approved', 'rejected', 'fulfilled', 'cancelled', name='request_status'),
               type_=sa.Enum('pending', 'manager_approved', 'it_approved', 'rejected', 'fulfilled', 'cancelled', name='requeststatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::request_status"))
    op.drop_constraint(op.f('asset_requests_user_id_fkey'), 'asset_requests', type_='foreignkey')
    op.create_foreign_key(None, 'asset_requests', 'users', ['user_id'], ['id'])
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               nullable=False)
    op.drop_index(op.f('idx_audit_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_logs')
    op.drop_constraint(op.f('fk_dept_head'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('holiday_calendar_holiday_date_is_optional_key'), 'holiday_calendar', type_='unique')
    op.drop_column('holiday_calendar', 'year')
    op.alter_column('it_inventory', 'asset_type',
               existing_type=postgresql.ENUM('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='asset_type'),
               type_=sa.Enum('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='assettype'),
               existing_nullable=False)
    op.alter_column('it_inventory', 'status',
               existing_type=postgresql.ENUM('available', 'assigned', 'in_repair', 'retired', 'lost', name='asset_status'),
               type_=sa.Enum('available', 'assigned', 'in_repair', 'retired', 'lost', name='assetstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'available'::asset_status"))
    op.alter_column('it_tickets', 'category',
               existing_type=postgresql.ENUM('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticket_category'),
               type_=sa.Enum('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticketcategory'),
               existing_nullable=False)
    op.alter_column('it_tickets', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='ticket_priority'),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='ticketpriority'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::ticket_priority"))
    op.alter_column('it_tickets', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'on_hold', 'resolved', 'closed', name='ticket_status'),
               type_=sa.Enum('open', 'in_progress', 'on_hold', 'resolved', 'closed', name='ticketstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::ticket_status"))
    op.drop_index(op.f('idx_tickets_assignee'), table_name='it_tickets')
    op.drop_index(op.f('idx_tickets_created'), table_name='it_tickets')
    op.drop_index(op.f('idx_tickets_status'), table_name='it_tickets')
    op.drop_index(op.f('idx_tickets_user'), table_name='it_tickets')
    op.drop_constraint(op.f('it_tickets_user_id_fkey'), 'it_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'it_tickets', 'users', ['user_id'], ['id'])
    op.alter_column('known_issues', 'category',
               existing_type=postgresql.ENUM('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticket_category'),
               type_=sa.Enum('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticketcategory'),
               existing_nullable=False)
    op.alter_column('leave_balances', 'leave_type',
               existing_type=postgresql.ENUM('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leave_type'),
               type_=sa.Enum('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leavetype'),
               existing_nullable=False)
    op.drop_constraint(op.f('leave_balances_user_id_fkey'), 'leave_balances', type_='foreignkey')
    op.create_foreign_key(None, 'leave_balances', 'users', ['user_id'], ['id'])
    op.add_column('leave_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('leave_requests', 'leave_type',
               existing_type=postgresql.ENUM('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leave_type'),
               type_=sa.Enum('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leavetype'),
               existing_nullable=False)
    op.alter_column('leave_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'cancelled', name='leave_status'),
               type_=sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leavestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::leave_status"))
    op.drop_index(op.f('idx_leaves_dates'), table_name='leave_requests')
    op.drop_index(op.f('idx_leaves_status'), table_name='leave_requests')
    op.drop_index(op.f('idx_leaves_user'), table_name='leave_requests')
    op.drop_constraint(op.f('leave_requests_user_id_fkey'), 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('payroll_records_user_id_fkey'), 'payroll_records', type_='foreignkey')
    op.create_foreign_key(None, 'payroll_records', 'users', ['user_id'], ['id'])
    op.alter_column('rag_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=False)
    op.drop_index(op.f('idx_rag_doc'), table_name='rag_chunks')
    op.drop_index(op.f('idx_rag_embedding'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('rag_documents', 'department',
               existing_type=postgresql.ENUM('hr', 'it', 'finance', 'general', name='doc_department'),
               type_=sa.Enum('hr', 'it', 'finance', 'general', name='docdepartment'),
               existing_nullable=False)
    op.alter_column('rag_documents', 'roles_allowed',
               existing_type=postgresql.ARRAY(postgresql.ENUM('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='user_role')),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("ARRAY['employee'::user_role]"))
    op.alter_column('reimbursements', 'category',
               existing_type=postgresql.ENUM('travel', 'internet', 'food', 'client_meeting', 'training', 'office_supplies', 'other', name='reimbursement_category'),
               type_=sa.Enum('travel', 'internet', 'food', 'client_meeting', 'training', 'office_supplies', 'other', name='reimbursementcategory'),
               existing_nullable=False)
    op.alter_column('reimbursements', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::bpchar"))
    op.alter_column('reimbursements', 'status',
               existing_type=postgresql.ENUM('draft', 'submitted', 'under_review', 'approved', 'rejected', 'paid', name='reimbursement_status'),
               type_=sa.Enum('draft', 'submitted', 'under_review', 'approved', 'rejected', 'paid', name='reimbursementstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::reimbursement_status"))
    op.drop_index(op.f('idx_reimb_status'), table_name='reimbursements')
    op.drop_index(op.f('idx_reimb_user'), table_name='reimbursements')
    op.drop_constraint(op.f('reimbursements_user_id_fkey'), 'reimbursements', type_='foreignkey')
    op.create_foreign_key(None, 'reimbursements', 'users', ['user_id'], ['id'])
    op.alter_column('role_permissions', 'role',
               existing_type=postgresql.ENUM('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='user_role'),
               type_=sa.Enum('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='userrole'),
               existing_nullable=False)
    op.alter_column('user_memory', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'inferred'::character varying"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='user_role'),
               type_=sa.Enum('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::user_role"))
    op.drop_index(op.f('idx_users_dept'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_manager'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_manager_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_manager_id_fkey'), 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_manager'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_dept'), 'users', ['department_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='userrole'),
               type_=postgresql.ENUM('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::user_role"))
    op.alter_column('user_memory', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'inferred'::character varying"))
    op.alter_column('role_permissions', 'role',
               existing_type=sa.Enum('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='userrole'),
               type_=postgresql.ENUM('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='user_role'),
               existing_nullable=False)
    op.drop_constraint(None, 'reimbursements', type_='foreignkey')
    op.create_foreign_key(op.f('reimbursements_user_id_fkey'), 'reimbursements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_reimb_user'), 'reimbursements', ['user_id'], unique=False)
    op.create_index(op.f('idx_reimb_status'), 'reimbursements', ['status'], unique=False)
    op.alter_column('reimbursements', 'status',
               existing_type=sa.Enum('draft', 'submitted', 'under_review', 'approved', 'rejected', 'paid', name='reimbursementstatus'),
               type_=postgresql.ENUM('draft', 'submitted', 'under_review', 'approved', 'rejected', 'paid', name='reimbursement_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::reimbursement_status"))
    op.alter_column('reimbursements', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::bpchar"))
    op.alter_column('reimbursements', 'category',
               existing_type=sa.Enum('travel', 'internet', 'food', 'client_meeting', 'training', 'office_supplies', 'other', name='reimbursementcategory'),
               type_=postgresql.ENUM('travel', 'internet', 'food', 'client_meeting', 'training', 'office_supplies', 'other', name='reimbursement_category'),
               existing_nullable=False)
    op.alter_column('rag_documents', 'roles_allowed',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(postgresql.ENUM('employee', 'manager', 'hr_team', 'it_team', 'finance_team', 'admin', name='user_role')),
               existing_nullable=False,
               existing_server_default=sa.text("ARRAY['employee'::user_role]"))
    op.alter_column('rag_documents', 'department',
               existing_type=sa.Enum('hr', 'it', 'finance', 'general', name='docdepartment'),
               type_=postgresql.ENUM('hr', 'it', 'finance', 'general', name='doc_department'),
               existing_nullable=False)
    op.create_index(op.f('idx_rag_embedding'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_rag_doc'), 'rag_chunks', ['document_id'], unique=False)
    op.alter_column('rag_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=True)
    op.drop_constraint(None, 'payroll_records', type_='foreignkey')
    op.create_foreign_key(op.f('payroll_records_user_id_fkey'), 'payroll_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key(op.f('leave_requests_user_id_fkey'), 'leave_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_leaves_user'), 'leave_requests', ['user_id'], unique=False)
    op.create_index(op.f('idx_leaves_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('idx_leaves_dates'), 'leave_requests', ['start_date', 'end_date'], unique=False)
    op.alter_column('leave_requests', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leavestatus'),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', 'cancelled', name='leave_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::leave_status"))
    op.alter_column('leave_requests', 'leave_type',
               existing_type=sa.Enum('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leavetype'),
               type_=postgresql.ENUM('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leave_type'),
               existing_nullable=False)
    op.drop_column('leave_requests', 'created_at')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.create_foreign_key(op.f('leave_balances_user_id_fkey'), 'leave_balances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('leave_balances', 'leave_type',
               existing_type=sa.Enum('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leavetype'),
               type_=postgresql.ENUM('casual', 'sick', 'earned', 'maternity', 'paternity', 'bereavement', 'compensatory', 'unpaid', name='leave_type'),
               existing_nullable=False)
    op.alter_column('known_issues', 'category',
               existing_type=sa.Enum('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticketcategory'),
               type_=postgresql.ENUM('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticket_category'),
               existing_nullable=False)
    op.drop_constraint(None, 'it_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('it_tickets_user_id_fkey'), 'it_tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_tickets_user'), 'it_tickets', ['user_id'], unique=False)
    op.create_index(op.f('idx_tickets_status'), 'it_tickets', ['status'], unique=False)
    op.create_index(op.f('idx_tickets_created'), 'it_tickets', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_tickets_assignee'), 'it_tickets', ['assigned_to'], unique=False)
    op.alter_column('it_tickets', 'status',
               existing_type=sa.Enum('open', 'in_progress', 'on_hold', 'resolved', 'closed', name='ticketstatus'),
               type_=postgresql.ENUM('open', 'in_progress', 'on_hold', 'resolved', 'closed', name='ticket_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::ticket_status"))
    op.alter_column('it_tickets', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='ticketpriority'),
               type_=postgresql.ENUM('low', 'medium', 'high', 'critical', name='ticket_priority'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::ticket_priority"))
    op.alter_column('it_tickets', 'category',
               existing_type=sa.Enum('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticketcategory'),
               type_=postgresql.ENUM('laptop', 'vpn', 'email', 'printer', 'network', 'software_install', 'hardware', 'access', 'other', name='ticket_category'),
               existing_nullable=False)
    op.alter_column('it_inventory', 'status',
               existing_type=sa.Enum('available', 'assigned', 'in_repair', 'retired', 'lost', name='assetstatus'),
               type_=postgresql.ENUM('available', 'assigned', 'in_repair', 'retired', 'lost', name='asset_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'available'::asset_status"))
    op.alter_column('it_inventory', 'asset_type',
               existing_type=sa.Enum('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='assettype'),
               type_=postgresql.ENUM('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='asset_type'),
               existing_nullable=False)
    op.add_column('holiday_calendar', sa.Column('year', sa.INTEGER(), sa.Computed('(EXTRACT(year FROM holiday_date))::integer', persisted=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('holiday_calendar_holiday_date_is_optional_key'), 'holiday_calendar', ['holiday_date', 'is_optional'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dept_head'), 'departments', 'users', ['head_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_audit_user'), 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_logs', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               nullable=True)
    op.drop_constraint(None, 'asset_requests', type_='foreignkey')
    op.create_foreign_key(op.f('asset_requests_user_id_fkey'), 'asset_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('asset_requests', 'status',
               existing_type=sa.Enum('pending', 'manager_approved', 'it_approved', 'rejected', 'fulfilled', 'cancelled', name='requeststatus'),
               type_=postgresql.ENUM('pending', 'manager_approved', 'it_approved', 'rejected', 'fulfilled', 'cancelled', name='request_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::request_status"))
    op.alter_column('asset_requests', 'asset_type',
               existing_type=sa.Enum('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='assettype'),
               type_=postgresql.ENUM('laptop', 'monitor', 'keyboard', 'mouse', 'vpn_token', 'software_license', 'headset', 'docking_station', 'other', name='asset_type'),
               existing_nullable=False)
    op.create_index(op.f('idx_approvals_entity'), 'approvals', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_approvals_approver'), 'approvals', ['approver_id', 'decision'], unique=False)
    op.alter_column('approvals', 'decision',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'escalated', name='approvaldecision'),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', 'escalated', name='approval_decision'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::approval_decision"))
    op.alter_column('approvals', 'entity_type',
               existing_type=sa.Enum('leave', 'asset_request', 'reimbursement', 'it_action', name='approvalentity'),
               type_=postgresql.ENUM('leave', 'asset_request', 'reimbursement', 'it_action', name='approval_entity'),
               existing_nullable=False)
    op.create_table('tax_declarations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fiscal_year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('regime', sa.VARCHAR(length=20), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False),
    sa.Column('section_80c', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('section_80d', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('hra_claimed', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lta_claimed', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('other_deductions', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tax_declarations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tax_declarations_pkey')),
    sa.UniqueConstraint('user_id', 'fiscal_year', name=op.f('tax_declarations_user_id_fiscal_year_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audit_logs_2024_01',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tool_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('audit_logs_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('audit_logs_2024_01_pkey'))
    )
    op.create_index(op.f('audit_logs_2024_01_user_id_created_at_idx'), 'audit_logs_2024_01', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('audit_logs_2024_01_action_created_at_idx'), 'audit_logs_2024_01', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('perm_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('granted', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('granted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('user_permission_overrides_granted_by_fkey')),
    sa.ForeignKeyConstraint(['perm_id'], ['permissions.id'], name=op.f('user_permission_overrides_perm_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_permission_overrides_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'perm_id', name=op.f('user_permission_overrides_pkey'))
    )
    op.create_table('audit_logs_2025_01',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tool_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('audit_logs_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('audit_logs_2025_01_pkey'))
    )
    op.create_index(op.f('audit_logs_2025_01_user_id_created_at_idx'), 'audit_logs_2025_01', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('audit_logs_2025_01_action_created_at_idx'), 'audit_logs_2025_01', ['action', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
